#!/usr/bin/ruby

=begin
Simple utility to make it easier to create Xresources configuration files.
This script will guide the user to configure:
1 - Colors
2 - URxvt configuration (Scrollbar, internal border, etc ...)
3 - Fonts
=end

require 'colorize'

# Number of items in the main menu
MENU = 3

# Automatic color configuration
def colorsAuto(configFile)
	print "Path of the image: "
	num = 16
	image = gets.chomp
	value = %x(magick #{image} -resize 25% -colors #{num} -unique-colors txt:)
	while value.lines.count <= 16 && num < 40
		value = %x(magick #{image} -resize 25% -colors #{num} -unique-colors txt:)
		num += 1
	end
	colors = value.split("\n")
	i = 1
	colorValue = []
	while i <= 16
		colorValue << colors[i].split(" ")[2]
		i += 1
	end
	configFile.puts "These colors were taken from the image #{image}"
	configFile.puts "!Background, Foreground and Cursor color"
	configFile.puts "*.foreground: #{colorValue[15]}"
	configFile.puts "*.background: #{colorValue[0]}"
	configFile.puts "*.cursorColor: #{colorValue[15]}"
	configFile.puts
	configFile.puts "! Black"
	configFile.puts "*.color0: #{colorValue[0]}"
	configFile.puts "*.color8: #{colorValue[8]}"
	configFile.puts
	configFile.puts "! Red"
	configFile.puts "*.color1: #{colorValue[1]}"
	configFile.puts "*.color9: #{colorValue[9]}"
	configFile.puts
	configFile.puts "! Green"
	configFile.puts "*.color2: #{colorValue[2]}"
	configFile.puts "*.color10: #{colorValue[10]}"
	configFile.puts
	configFile.puts "! Yellow"
	configFile.puts "*.color3: #{colorValue[3]}"
	configFile.puts "*.color11: #{colorValue[11]}"
	configFile.puts
	configFile.puts "! Blue"
	configFile.puts "*.color4: #{colorValue[4]}"
	configFile.puts "*.color12: #{colorValue[12]}"
	configFile.puts
	configFile.puts "! Magenta"
	configFile.puts "*.color5: #{colorValue[5]}"
	configFile.puts "*.color13: #{colorValue[13]}"
	configFile.puts
	configFile.puts "! Cyan"
	configFile.puts "*.color6: #{colorValue[6]}"
	configFile.puts "*.color14: #{colorValue[14]}"
	configFile.puts
	configFile.puts "! White"
	configFile.puts "*.color7: #{colorValue[7]}"
	configFile.puts "*.color15: #{colorValue[15]}"

	puts
	puts "Done configuring colors!".green
	puts "Your new color palette is:"
	puts colorValue
end

# Manual color configuration
def colorsManual(configFile)
	configFile.puts "! Background, foreground and cursor color"
	configFile.puts

	print "Hex for foreground color: "
	color = gets
	configFile.puts "*.foreground: #{color}"

	print "Hex for background color: "
	color = gets
	configFile.puts "*.background: #{color}"

	print "Hex for cursor color: "
	color = gets
	configFile.puts "*.cursorColor: #{color}"

	configFile.puts
	configFile.puts "! Black"

	print "Hex for black color: "
	color = gets
	configFile.puts "*.color0: #{color}"

	print "Hex for bright black color: "
	color = gets
	configFile.puts "*.color8: #{color}"

	configFile.puts
	configFile.puts "! Red"

	print "Hex for "
	print "red".red
	print " color: "
	color = gets
	configFile.puts "*.color1: #{color}"

	print "Hex for "
	print "bright red".red
	print " color: "
	color = gets
	configFile.puts "*.color9: #{color}"

	configFile.puts
	configFile.puts "! Green"

	print "Hex for "
	print "green".green
	print " color: "
	color = gets
	configFile.puts "*.color2: #{color}"

	print "Hex for "
	print "bright green".green
	print " color: "
	color = gets
	configFile.puts "*.color10: #{color}"

	configFile.puts
	configFile.puts "! Yellow"

	print "Hex for "
	print "yellow".yellow
	print " color: "
	color = gets
	configFile.puts "*.color3: #{color}"

	print "Hex for "
	print "bright yellow".yellow
	print " color: "
	color = gets
	configFile.puts "*.color11: #{color}"

	configFile.puts
	configFile.puts "! Blue"

	print "Hex for "
	print "blue".blue
	print " color: "
	color = gets
	configFile.puts "*.color4: #{color}"
	
	print "Hex for "
	print "bright blue".blue
	print " color: "
	color = gets
	configFile.puts "*.color12: #{color}"

	configFile.puts
	configFile.puts "! Magenta"

	print "Hex for "
	print "magenta".magenta
	print " color: "
	color = gets
	configFile.puts "*.color5: #{color}"

	print "Hex for "
	print "bright magenta".magenta
	print " color: "
	color = gets
	configFile.puts "*.color13: #{color}"

	configFile.puts
	configFile.puts "! Cyan"

	print "Hex for "
	print "cyan".cyan
	print " color: "
	color = gets
	configFile.puts "*.color6: #{color}"

	print "Hex for "
	print "bright cyan".cyan
	print " color: "
	color = gets
	configFile.puts "*.color14: #{color}"

	configFile.puts
	configFile.puts "! White"

	print "Hex for white color: "
	color = gets
	configFile.puts "*.color7: #{color}"

	print "Hex for bright white color: "
	color = gets
	configFile.puts "*.color15: #{color}"

	puts
	puts "Done configuring colors!".green
end

def colors(configFile)
	puts
	puts "How do you want to configure colors?".yellow
	puts "M for manual configuration"
	puts "A for automatic configuration giving an image"
	correct = false
	while !correct
		answer = gets
		if answer.chomp == "M" || answer.chomp == "m"
			colorsManual(configFile)
			correct = true
		elsif answer.chomp == "A" || answer.chomp == "a"
			colorsAuto(configFile)
			correct = true
		else
			puts "Option not recognized, write 'M' or 'A'"
		end
	end
end

def urxvt(configFile)
	correct = false
	configFile.puts
	configFile.puts "! URxvt configuration"
	while !correct
		print "Do you want to have scrollbar? (y/n): "
		answer = gets
		if answer.chomp == "y"
			configFile.puts "URxvt.scrollBar: true"
			correct = true
		elsif answer.chomp == "n"
			configFile.puts "URxvt.scrollBar: false"
			correct = true;
		else
			puts "Answer was not recognized, write 'y' or 'n'".red
		end
	end
	print "Internal border size (in pixels): "
	answer = gets
	configFile.puts "URxvt.internalBorder: #{answer}"
	puts
	puts "Done configuring URxvt!".green
end

def fonts(configFile)
	configFile.puts
	configFile.puts "! Font configuration"
	correct = false
	while !correct
		print "Do you want to activate antialiasing? (y/n): "
		answer = gets
		if answer.chomp == "y"
			configFile.puts "Xft.antialias: true"
			correct = true
		elsif answer.chomp == "n"
			configFile.puts "Xft.antialias: false"
			correct = true
		else
			puts "Answer not recognized, write 'y' or 'n'".red
		end
	end
	correct = false
	while !correct
		print "Do you want to activate autohint? (y/n): "
		answer = gets
		if answer.chomp == "y"
			configFile.puts "Xft.autohint: true"
			correct = true
		elsif answer.chomp == "n"
			configFile.puts "Xft.autohint: false"
			correct = true
		else
			puts "Answer not recognized, write 'y' or 'n'".red
		end
	end
	correct = false
	while !correct
		print "Do you want to activate hinting? (y/n): "
		answer = gets
		if answer.chomp == "y"
			configFile.puts "Xft.hinting: true"
			correct = true
		elsif answer.chomp == "n"
			configFile.puts "Xft.hinting: false"
			correct = true
		else
			puts "Answer not recognized, write 'y' or 'n'".red
		end
	end
	print "What hinting style do you want to use?: "
	answer = gets
	configFile.puts "Xft.hintstyle: #{answer}"
	
	print "What lcdfilter do you want to use?: "
	answer = gets
	configFile.puts "Xft.lcdfilter: #{answer}"

	print "What rgba value do you want to use?: "
	answer = gets
	configFile.puts "Xft.rgba: #{answer}"

	puts
	puts "Done configuring fonts!".green
end

puts "Welcome to Ruby Ricer".magenta
puts
puts "First of all, select the location where your new config file will be saved:"

path = gets

print "Creating the file called '#{path.chomp}' ... "

# Create a new file with the given name
configFile = File.new( path.chomp,  File::CREAT|File::TRUNC|File::RDWR, 0644);
puts "DONE".green

configFile.puts "! Automatically created by Ruby Ricer by end222"
configFile.puts

i = MENU
todo = [true,true,true]
fin = false

# Main menu
while i > 0 && !fin 
	puts
	puts "Choose what you want to configure:".yellow
	if todo[0]
		puts "1 - Configure Colors"
	end
	if todo[1]
		puts "2 - Configure URxvt"
	end
	if todo[2]
		puts "3 - Configure Fonts"
	end
	puts "4 - I do not want to configure anything else"
	puts
	puts "Choose an option (1 - 4)"
	option = gets

	if option.to_i == 1 && todo[0]
		colors(configFile)
		todo[0] = false
		i -= 1
	elsif option.to_i == 2 && todo[1]
		urxvt(configFile)
		todo[1] = false
		i -= 1
	elsif option.to_i == 3 && todo[2]
		fonts(configFile)
		todo[2] = false
		i -= 1
	elsif option.to_i == 4
		fin = true
	else
		puts "Couldn't recognize option: #{option}".red
	end
end

puts "You finished configuring it! Enjoy the new configuration! :)"
